name: Java CI with Maven

# Trigger the workflow on push or pull request events to the main branch
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Check out the repository code
    - name: Check out repository code
      uses: actions/checkout@v2

    # Set up JDK 11
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin' # Use 'temurin' or another distribution if preferred
        java-version: '11'

    # Load environment variables (from GitHub secrets)
    - name: Load environment variables
      run: echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> $GITHUB_ENV

    # Build the project with Maven
    - name: Build with Maven
      run: mvn -B clean install

    # Run tests with Maven
    - name: Test with Maven
      run: mvn test
